### ISSUE TITLE
sort other data types than numbers in `sortArr` method

### ISSUE THREAD

**Issue by yactouat** [yactouat/search_algos#1]

**Comment by ryuusama09** [comment]
@yactouat , would you specify where this needs to be implemented ?

**Comment by yactouat** [comment]
hey @ryuusama09 , this would be implemented here => https://github.com/yactouat/search_algos/blob/e353f7eea7db27273ab1e7eef23ca5cd46b164dc/src/binary.ts#L47 (with tests) , for instance by sorting strings in addition to numbers

**Comment by ryuusama09** [comment]
@yactouat  got it , so you want the same function overloaded with different parameters ? or write different fucntions which does the same job ?

**Comment by yactouat** [comment]
hey @ryuusama09 , ideally one should be able to use the same function as an entry point, but it can of course call other functions from within itself

**Comment by ryuusama09** [comment]
so irrespective of any data type is passed in , its comparator should be able to sort them ? . for eg [18 , 'a'] @yactouat

**Comment by yactouat** [comment]
@ryuusama09 , 🤔 it's either that or throwing an exception... I would incline to prefer exceptions to specifically give feedback to the user that one ought to sort values of the same types, what do you think ?

**Comment by ryuusama09** [comment]
> @ryuusama09 , 🤔 it's either that or throwing an exception... I would incline to prefer exceptions to specifically give feedback to the user that one ought to sort values of the same types, what do you think ?

I would agree too , sorting the same data types makes sense !

**Comment by yactouat** [comment]
si let's roll with exceptions then !

**Comment by ryuusama09** [comment]
alright !! , so currently the sortarr sorts numbers , but why exactly are you returning b-a ? .

**Comment by yactouat** [comment]
hey @ryuusama09 , returning b-a because I want the array to be sorted ASC (instead of DESC), or maybe an option to chose which order would be good ?

**Comment by ryuusama09** [comment]
![image](https://user-images.githubusercontent.com/80237556/207381011-63e87ac7-0ef2-4385-bf6b-d276bdcfac05.png)
this part is your comparator right ? . so over here returning b - a  doesnt really makes sense . Or if i am misunderstanding it , can you show how on some example how it works ?
