### ISSUE TITLE
thank and show contributors badges in the readme

### ISSUE THREAD

**Issue by yactouat** [yactouat/search_algos#21]

**Comment by agung2001** [comment]
hi @yactouat 👋😄
I wanna help adding contributors badges if that's ok for you.
I'm gonna add this code to the `README.md` file
```README.md
## Contributors
<img src="https://contrib.rocks/image?repo=yactouat/search_algos" />
```

**Comment by yactouat** [comment]
hey @agung2001 , really it's that easy ?? haha
well go for it and thanks for contributing ;)

**Comment by agung2001** [comment]
hi @yactouat haha yeah unfortunately it's that easy 😄
anyway, I've created PR which contains an updated README.md file, you can review it here : 
- #23 

just let me know if u still had any questions ok 😄👍
cheers mate 🍻

**Comment by yactouat** [comment]
@agung2001 thanks !
