### ISSUE TITLE
implement CI/CD pipeline

### ISSUE THREAD

**Issue by yactouat** [yactouat/search_algos#4]

**Comment by ShashwatAgrawal20** [comment]
take

**Comment by yactouat** [comment]
@ShashwatAgrawal20 , thx mate, I basically would like to run tests at each commit or PR to main branch

**Comment by ShashwatAgrawal20** [comment]
@yactouat which types of tests? 

some basic linting tests or something else?

**Comment by yactouat** [comment]
@ShashwatAgrawal20 , the tests that are in the `tests` folder of the project ;)

**Comment by yactouat** [comment]
basically, this would require to run `npm run test`  in the CI

**Comment by ShashwatAgrawal20** [comment]
Would implement it soon, give me some hours.

**Comment by yactouat** [comment]
of course, there is no rush, thx for contributing !
